version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kozsd_mail
      POSTGRES_USER: kozsd_admin
      POSTGRES_PASSWORD: secure_password_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kozsd-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kozsd-network

  # MinIO (S3 Alternative for local development)
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: kozsd_minio
      MINIO_ROOT_PASSWORD: secure_minio_123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - kozsd-network

  # Backend Service (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://kozsd_admin:secure_password_123@postgres:5432/kozsd_mail
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - kozsd-network

  # Frontend Service (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - kozsd-network

  # Admin Panel (Development)
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - kozsd-network

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  kozsd-network:
    driver: bridge